services:
  server:
    build: ./server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATA_PATH=/app/data/last-match.json
      - SETTINGS_PATH=/app/data/settings.json
    volumes:
      - ./data:/app/data
    networks: [appnet]

  web:
    build: ./web
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on: [server]
    networks: [appnet]

networks:
  appnet:
    driver: bridge